In [1]:
import pandas as pd

data = {'Nome':['José', 'Maria', 'João', 'Ana', 'João'],'Idade':[50,34,29,15,3]}
df = pd.DataFrame(data)
print(df)
print(type(df))

    Nome  Idade
0   José     50
1  Maria     34
2   João     29
3    Ana     15
4   João      3
<class 'pandas.core.frame.DataFrame'>

In [2]:
df

    Nome  Idade
0   José     50
1  Maria     34
2   João     29
3    Ana     15
4   João      3

In [3]:
df.dtypes

Nome     object
Idade     int64
dtype: object

In [4]:
print(df.Idade)
print(type(df.Idade))

0    50
1    34
2    29
3    15
4     3
Name: Idade, dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
print(df["Idade"])

0    50
1    34
2    29
3    15
4     3
Name: Idade, dtype: int64

In [6]:
print(df.values)

[['José' 50]
 ['Maria' 34]
 ['João' 29]
 ['Ana' 15]
 ['João' 3]]

In [9]:
print(df["Idade"].values)

[50 34 29 15  3]

In [8]:
print(df.columns)

Index(['Nome', 'Idade'], dtype='object')

In [9]:
print(df.index)

RangeIndex(start=0, stop=5, step=1)

In [10]:
# https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html

df["Nome"].unique()

array(['José', 'Maria', 'João', 'Ana'], dtype=object)

In [13]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html

df["Nome"].value_counts()

João     2
José     1
Maria    1
Ana      1
Name: Nome, dtype: int64

In [14]:
print(df.sort_values(by="Nome"))

    Nome  Idade
3    Ana     15
0   José     50
2   João     29
4   João      3
1  Maria     34

In [15]:
print(df[df["Idade"]>=18])

    Nome  Idade
0   José     50
1  Maria     34
2   João     29

In [16]:
# https://pandas.pydata.org/docs/user_guide/indexing.html#boolean-indexing

print(df["Idade"]>=18)

0     True
1     True
2     True
3    False
4    False
Name: Idade, dtype: bool

In [17]:
# https://pandas.pydata.org/docs/user_guide/indexing.html#the-where-method-and-masking

print(df.where(df["Idade"]>=18))

    Nome  Idade
0   José   50.0
1  Maria   34.0
2   João   29.0
3    NaN    NaN
4    NaN    NaN

In [18]:
# operadores lógicos https://pandas.pydata.org/docs/user_guide/indexing.html#boolean-indexing
# string https://pandas.pydata.org/docs/user_guide/basics.html#vectorized-string-methods

print(df[ (df["Idade"]>=18) & (df["Nome"].str[0]=='J') ]  )

   Nome  Idade
0  José     50
2  João     29

In [19]:
# https://pandas.pydata.org/docs/user_guide/groupby.html

print(df.groupby("Nome").groups)

print(df.groupby("Nome").sum())

{'Ana': [3], 'José': [0], 'João': [2, 4], 'Maria': [1]}
       Idade
Nome
Ana       15
José      50
João      32
Maria     34

In [11]:
# https://pandas.pydata.org/docs/user_guide/dsintro.html#column-selection-addition-deletion

df["AnoNascimento"] = 2023 - df["Idade"]
print(df)

    Nome  Idade  AnoNascimento
0   José     50           1973
1  Maria     34           1989
2   João     29           1994
3    Ana     15           2008
4   João      3           2020

In [21]:
print(df)

print(df[["Nome","AnoNascimento"]])

    Nome  Idade  AnoNascimento
0   José     50           1973
1  Maria     34           1989
2   João     29           1994
3    Ana     15           2008
4   João      3           2020
    Nome  AnoNascimento
0   José           1973
1  Maria           1989
2   João           1994
3    Ana           2008
4   João           2020